//
// Created by yechentide on 2025/04/13
//

import CoreGraphics

extension MCBiomeType {
    public var color: CGColor {
        switch self {
            case .unknown:                                               CGColor.from(red:   0, green:   0, blue:   0, alpha: 0)
            case .ocean:                                                 CGColor.from(red:   0, green:   0, blue: 112)
            case .plains:                                                CGColor.from(red: 141, green: 179, blue:  96)
            case .desert:                                                CGColor.from(red: 250, green: 148, blue:  24)
            case .extremeHills:                                          CGColor.from(red:  96, green:  96, blue:  96)
            case .forest:                                                CGColor.from(red:   5, green: 102, blue:  33)
            case .taiga:                                                 CGColor.from(red:  11, green: 102, blue:  89)
            case .swampland:                                             CGColor.from(red:   7, green: 249, blue: 178)
            case .river:                                                 CGColor.from(red:   0, green:   0, blue: 255)
            case .hell:                                                  CGColor.from(red: 191, green:  59, blue:  59)
            case .theEnd:                                                CGColor.from(red: 128, green: 128, blue: 255)
            case .legacyFrozenOcean:                                     CGColor.from(red: 112, green: 112, blue: 214)
            case .frozenRiver:                                           CGColor.from(red: 160, green: 160, blue: 255)
            case .icePlains:                                             CGColor.from(red: 255, green: 255, blue: 255)
            case .iceMountains:                                          CGColor.from(red: 160, green: 160, blue: 160)
            case .mushroomIsland:                                        CGColor.from(red: 255, green:   0, blue: 255)
            case .mushroomIslandShore:                                   CGColor.from(red: 160, green:   0, blue: 255)
            case .beach:                                                 CGColor.from(red: 250, green: 222, blue:  85)
            case .desertHills:                                           CGColor.from(red: 210, green:  95, blue:  18)
            case .forestHills:                                           CGColor.from(red:  34, green:  85, blue:  28)
            case .taigaHills:                                            CGColor.from(red:  22, green:  57, blue:  51)
            case .extremeHillsEdge:                                      CGColor.from(red: 114, green: 120, blue: 154)
            case .jungle:                                                CGColor.from(red:  83, green: 123, blue:   9)
            case .jungleHills:                                           CGColor.from(red:  44, green:  66, blue:   5)
            case .jungleEdge:                                            CGColor.from(red:  98, green: 139, blue:  23)
            case .deepOcean:                                             CGColor.from(red:   0, green:   0, blue:  48)
            case .stoneBeach:                                            CGColor.from(red: 162, green: 162, blue: 132)
            case .coldBeach:                                             CGColor.from(red: 250, green: 240, blue: 192)
            case .birchForest:                                           CGColor.from(red:  48, green: 116, blue:  68)
            case .birchForestHills:                                      CGColor.from(red:  31, green:  95, blue:  50)
            case .roofedForest:                                          CGColor.from(red:  64, green:  81, blue:  26)
            case .coldTaiga:                                             CGColor.from(red:  49, green:  85, blue:  74)
            case .coldTaigaHills:                                        CGColor.from(red:  36, green:  63, blue:  54)
            case .megaTaiga:                                             CGColor.from(red:  89, green: 102, blue:  81)
            case .megaTaigaHills:                                        CGColor.from(red:  69, green:  79, blue:  62)
            case .extremeHillsPlusTrees:                                 CGColor.from(red:  80, green: 112, blue:  80)
            case .savanna:                                               CGColor.from(red: 189, green: 178, blue:  95)
            case .savannaPlateau:                                        CGColor.from(red: 167, green: 157, blue: 100)
            case .mesa:                                                  CGColor.from(red: 217, green:  69, blue:  21)
            case .mesaPlateauStone:                                      CGColor.from(red: 176, green: 151, blue: 101)
            case .mesaPlateau:                                           CGColor.from(red: 202, green: 140, blue: 101)
            case .warmOcean:                                             CGColor.from(red:   0, green:   0, blue: 172)
            case .deepWarmOcean:                                         CGColor.from(red:   0, green:   0, blue:  80)
            case .lukewarmOcean:                                         CGColor.from(red:   0, green:   0, blue: 144)
            case .deepLukewarmOcean:                                     CGColor.from(red:   0, green:   0, blue:  64)
            case .coldOcean:                                             CGColor.from(red:  32, green:  32, blue: 112)
            case .deepColdOcean:                                         CGColor.from(red:  32, green:  32, blue:  56)
            case .frozenOcean:                                           CGColor.from(red:  64, green:  64, blue: 144)
            case .deepFrozenOcean:                                       CGColor.from(red:  64, green:  64, blue: 144)
            case .bambooJungle:                                          CGColor.from(red: 118, green: 142, blue:  20)
            case .bambooJungleHills:                                     CGColor.from(red:  59, green:  71, blue:  10)
            case .sunflowerPlains:                                       CGColor.from(red: 181, green: 219, blue: 136)
            case .desertMutated:                                         CGColor.from(red: 255, green: 188, blue:  64)
            case .extremeHillsMutated:                                   CGColor.from(red: 136, green: 136, blue: 136)
            case .flowerForest:                                          CGColor.from(red:  45, green: 142, blue:  73)
            case .taigaMutated:                                          CGColor.from(red:  51, green: 142, blue: 129)
            case .swamplandMutated:                                      CGColor.from(red:  47, green: 255, blue: 218)
            case .icePlainsSpikes:                                       CGColor.from(red: 180, green: 220, blue: 220)
            case .jungleMutated:                                         CGColor.from(red: 123, green: 163, blue:  49)
            case .jungleEdgeMutated:                                     CGColor.from(red: 138, green: 179, blue:  63)
            case .birchForestMutated:                                    CGColor.from(red:  88, green: 156, blue: 108)
            case .birchForestHillsMutated:                               CGColor.from(red:  71, green: 135, blue:  90)
            case .roofedForestMutated:                                   CGColor.from(red: 104, green: 121, blue:  66)
            case .coldTaigaMutated:                                      CGColor.from(red:  89, green: 125, blue: 114)
            case .redwoodTaigaMutated:                                   CGColor.from(red: 129, green: 142, blue: 121)
            case .redwoodTaigaHillsMutated:                              CGColor.from(red: 109, green: 119, blue: 102)
            case .extremeHillsPlusTreesMutated:                          CGColor.from(red: 120, green: 152, blue: 120)
            case .savannaMutated:                                        CGColor.from(red: 229, green: 218, blue: 135)
            case .savannaPlateauMutated:                                 CGColor.from(red: 207, green: 197, blue: 140)
            case .mesaBryce:                                             CGColor.from(red: 255, green: 109, blue:  61)
            case .mesaPlateauStoneMutated:                               CGColor.from(red: 216, green: 191, blue: 141)
            case .mesaPlateauMutated:                                    CGColor.from(red: 242, green: 180, blue: 141)
            case .soulsandValley:                                        CGColor.from(red:  94, green:  56, blue:  48)
            case .crimsonForest:                                         CGColor.from(red: 221, green:   8, blue:   8)
            case .warpedForest:                                          CGColor.from(red:  73, green: 144, blue: 123)
            case .basaltDeltas:                                          CGColor.from(red:  64, green:  54, blue:  54)
            case .jaggedPeaks:                                           CGColor.from(red: 227, green: 236, blue: 237)
            case .frozenPeaks:                                           CGColor.from(red: 234, green: 251, blue: 251)
            case .snowySlopes:                                           CGColor.from(red: 218, green: 241, blue: 241)
            case .grove:                                                 CGColor.from(red: 223, green: 236, blue: 229)
            case .meadow:                                                CGColor.from(red: 140, green: 164, blue: 112)
            case .lushCaves:                                             CGColor.from(red: 223, green: 150, blue:  52)
            case .dripstoneCaves:                                        CGColor.from(red: 193, green: 165, blue: 143)
            case .stonyPeaks:                                            CGColor.from(red: 209, green: 209, blue: 209)
            case .deepDark:                                              CGColor.from(red:   0, green:   0, blue:   0)
            case .mangroveSwamp:                                         CGColor.from(red:  36, green: 196, blue: 142)
            case .cherryGrove:                                           CGColor.from(red: 247, green: 185, blue: 220)
            case .paleGarden:                                            CGColor.from(red: 108, green: 111, blue: 150)
        }
    }
}
