//
// Created by yechentide on 2025/03/21
//
public enum MCEducationBlockType: String, CaseIterable, Sendable {
    // Others
    case board                              = "minecraft:board"
    case chalkboard                         = "minecraft:chalkboard"

    // Items Tab
    case elementConstructor                 = "minecraft:element_constructor"
    case compoundCreator                    = "minecraft:compound_creator"
    case labTable                           = "minecraft:lab_table"
    case materialReducer                    = "minecraft:material_reducer"

    case underwaterTorch                    = "minecraft:underwater_torch"
    case underwaterTnt                      = "minecraft:underwater_tnt"
    case chemicalHeat                       = "minecraft:chemical_heat"
    case coloredTorchBlue                   = "minecraft:colored_torch_blue"
    case coloredTorchPurple                 = "minecraft:colored_torch_purple"
    case coloredTorchRed                    = "minecraft:colored_torch_red"
    case coloredTorchGreen                  = "minecraft:colored_torch_green"

    case hardGlass                          = "minecraft:hard_glass"
    case hardWhiteStainedGlass              = "minecraft:hard_white_stained_glass"
    case hardOrangeStainedGlass             = "minecraft:hard_orange_stained_glass"
    case hardMagentaStainedGlass            = "minecraft:hard_magenta_stained_glass"
    case hardLightBlueStainedGlass          = "minecraft:hard_light_blue_stained_glass"
    case hardYellowStainedGlass             = "minecraft:hard_yellow_stained_glass"
    case hardLimeStainedGlass               = "minecraft:hard_lime_stained_glass"
    case hardPinkStainedGlass               = "minecraft:hard_pink_stained_glass"
    case hardGrayStainedGlass               = "minecraft:hard_gray_stained_glass"
    case hardLightGrayStainedGlass          = "minecraft:hard_light_gray_stained_glass"
    case hardCyanStainedGlass               = "minecraft:hard_cyan_stained_glass"
    case hardPurpleStainedGlass             = "minecraft:hard_purple_stained_glass"
    case hardBlueStainedGlass               = "minecraft:hard_blue_stained_glass"
    case hardBrownStainedGlass              = "minecraft:hard_brown_stained_glass"
    case hardGreenStainedGlass              = "minecraft:hard_green_stained_glass"
    case hardRedStainedGlass                = "minecraft:hard_red_stained_glass"
    case hardBlackStainedGlass              = "minecraft:hard_black_stained_glass"

    case hardGlassPane                      = "minecraft:hard_glass_pane"
    case hardWhiteStainedGlassPane          = "minecraft:hard_white_stained_glass_pane"
    case hardOrangeStainedGlassPane         = "minecraft:hard_orange_stained_glass_pane"
    case hardMagentaStainedGlassPane        = "minecraft:hard_magenta_stained_glass_pane"
    case hardLightBlueStainedGlassPane      = "minecraft:hard_light_blue_stained_glass_pane"
    case hardYellowStainedGlassPane         = "minecraft:hard_yellow_stained_glass_pane"
    case hardLimeStainedGlassPane           = "minecraft:hard_lime_stained_glass_pane"
    case hardPinkStainedGlassPane           = "minecraft:hard_pink_stained_glass_pane"
    case hardGrayStainedGlassPane           = "minecraft:hard_gray_stained_glass_pane"
    case hardLightGrayStainedGlassPane      = "minecraft:hard_light_gray_stained_glass_pane"
    case hardCyanStainedGlassPane           = "minecraft:hard_cyan_stained_glass_pane"
    case hardPurpleStainedGlassPane         = "minecraft:hard_purple_stained_glass_pane"
    case hardBlueStainedGlassPane           = "minecraft:hard_blue_stained_glass_pane"
    case hardBrownStainedGlassPane          = "minecraft:hard_brown_stained_glass_pane"
    case hardGreenStainedGlassPane          = "minecraft:hard_green_stained_glass_pane"
    case hardRedStainedGlassPane            = "minecraft:hard_red_stained_glass_pane"
    case hardBlackStainedGlassPane          = "minecraft:hard_black_stained_glass_pane"

    // Construction Tab
    case element0                           = "minecraft:element_0"
    case element1                           = "minecraft:element_1"
    case element2                           = "minecraft:element_2"
    case element3                           = "minecraft:element_3"
    case element4                           = "minecraft:element_4"
    case element5                           = "minecraft:element_5"
    case element6                           = "minecraft:element_6"
    case element7                           = "minecraft:element_7"
    case element8                           = "minecraft:element_8"
    case element9                           = "minecraft:element_9"
    case element10                          = "minecraft:element_10"
    case element11                          = "minecraft:element_11"
    case element12                          = "minecraft:element_12"
    case element13                          = "minecraft:element_13"
    case element14                          = "minecraft:element_14"
    case element15                          = "minecraft:element_15"
    case element16                          = "minecraft:element_16"
    case element17                          = "minecraft:element_17"
    case element18                          = "minecraft:element_18"
    case element19                          = "minecraft:element_19"
    case element20                          = "minecraft:element_20"
    case element21                          = "minecraft:element_21"
    case element22                          = "minecraft:element_22"
    case element23                          = "minecraft:element_23"
    case element24                          = "minecraft:element_24"
    case element25                          = "minecraft:element_25"
    case element26                          = "minecraft:element_26"
    case element27                          = "minecraft:element_27"
    case element28                          = "minecraft:element_28"
    case element29                          = "minecraft:element_29"
    case element30                          = "minecraft:element_30"
    case element31                          = "minecraft:element_31"
    case element32                          = "minecraft:element_32"
    case element33                          = "minecraft:element_33"
    case element34                          = "minecraft:element_34"
    case element35                          = "minecraft:element_35"
    case element36                          = "minecraft:element_36"
    case element37                          = "minecraft:element_37"
    case element38                          = "minecraft:element_38"
    case element39                          = "minecraft:element_39"
    case element40                          = "minecraft:element_40"
    case element41                          = "minecraft:element_41"
    case element42                          = "minecraft:element_42"
    case element43                          = "minecraft:element_43"
    case element44                          = "minecraft:element_44"
    case element45                          = "minecraft:element_45"
    case element46                          = "minecraft:element_46"
    case element47                          = "minecraft:element_47"
    case element48                          = "minecraft:element_48"
    case element49                          = "minecraft:element_49"
    case element50                          = "minecraft:element_50"
    case element51                          = "minecraft:element_51"
    case element52                          = "minecraft:element_52"
    case element53                          = "minecraft:element_53"
    case element54                          = "minecraft:element_54"
    case element55                          = "minecraft:element_55"
    case element56                          = "minecraft:element_56"
    case element57                          = "minecraft:element_57"
    case element58                          = "minecraft:element_58"
    case element59                          = "minecraft:element_59"
    case element60                          = "minecraft:element_60"
    case element61                          = "minecraft:element_61"
    case element62                          = "minecraft:element_62"
    case element63                          = "minecraft:element_63"
    case element64                          = "minecraft:element_64"
    case element65                          = "minecraft:element_65"
    case element66                          = "minecraft:element_66"
    case element67                          = "minecraft:element_67"
    case element68                          = "minecraft:element_68"
    case element69                          = "minecraft:element_69"
    case element70                          = "minecraft:element_70"
    case element71                          = "minecraft:element_71"
    case element72                          = "minecraft:element_72"
    case element73                          = "minecraft:element_73"
    case element74                          = "minecraft:element_74"
    case element75                          = "minecraft:element_75"
    case element76                          = "minecraft:element_76"
    case element77                          = "minecraft:element_77"
    case element78                          = "minecraft:element_78"
    case element79                          = "minecraft:element_79"
    case element80                          = "minecraft:element_80"
    case element81                          = "minecraft:element_81"
    case element82                          = "minecraft:element_82"
    case element83                          = "minecraft:element_83"
    case element84                          = "minecraft:element_84"
    case element85                          = "minecraft:element_85"
    case element86                          = "minecraft:element_86"
    case element87                          = "minecraft:element_87"
    case element88                          = "minecraft:element_88"
    case element89                          = "minecraft:element_89"
    case element90                          = "minecraft:element_90"
    case element91                          = "minecraft:element_91"
    case element92                          = "minecraft:element_92"
    case element93                          = "minecraft:element_93"
    case element94                          = "minecraft:element_94"
    case element95                          = "minecraft:element_95"
    case element96                          = "minecraft:element_96"
    case element97                          = "minecraft:element_97"
    case element98                          = "minecraft:element_98"
    case element99                          = "minecraft:element_99"
    case element100                         = "minecraft:element_100"
    case element101                         = "minecraft:element_101"
    case element102                         = "minecraft:element_102"
    case element103                         = "minecraft:element_103"
    case element104                         = "minecraft:element_104"
    case element105                         = "minecraft:element_105"
    case element106                         = "minecraft:element_106"
    case element107                         = "minecraft:element_107"
    case element108                         = "minecraft:element_108"
    case element109                         = "minecraft:element_109"
    case element110                         = "minecraft:element_110"
    case element111                         = "minecraft:element_111"
    case element112                         = "minecraft:element_112"
    case element113                         = "minecraft:element_113"
    case element114                         = "minecraft:element_114"
    case element115                         = "minecraft:element_115"
    case element116                         = "minecraft:element_116"
    case element117                         = "minecraft:element_117"
    case element118                         = "minecraft:element_118"
}

extension MCEducationBlockType {
    var isFlower: Bool { false }

    var isPlant: Bool { false }

    var isTransparent: Bool {
        switch self {
            default:
                false
        }
    }
}
