import Foundation

extension MCBlockType: CustomStringConvertible {
    public var description: String {
        switch self {
            case .unknown:                                  return "minecraft:unknown"
            case .air:                                      return "minecraft:air"
            case .bedrock:                                  return "minecraft:bedrock"
            case .fire:                                     return "minecraft:fire"
            case .water:                                    return "minecraft:water"
            case .lava:                                     return "minecraft:lava"
            case .flowingWater:                             return "minecraft:flowing_water"
            case .flowingLava:                              return "minecraft:flowing_lava"
            case .obsidian:                                 return "minecraft:obsidian"
            case .cryingObsidian:                           return "minecraft:crying_obsidian"

            /* ---------- ---------- ---------- Overworld ---------- ---------- ---------- */
            case .grass:                                    return "minecraft:grass"
            case .dirt:                                     return "minecraft:dirt"
            case .coarseDirt:                               return "minecraft:dirt"
            case .farmland:                                 return "minecraft:farmland"
            case .dirtPath:                                 return "minecraft:grass_path"
            case .podzol:                                   return "minecraft:podzol"
            case .mycelium:                                 return "minecraft:mycelium"

            case .gravel:                                   return "minecraft:gravel"
            case .sand:                                     return "minecraft:sand"
            case .redSand:                                  return "minecraft:sand"
            case .suspiciousGravel:                         return "minecraft:suspicious_gravel"
            case .suspiciousSand:                           return "minecraft:suspicious_sand"

            case .web:                                      return "minecraft:web"
            case .beeNest:                                  return "minecraft:bee_nest"

            case .mobSpawner:                               return "minecraft:mob_spawner"
            case .infestedStone:                            return "minecraft:monster_egg"
            case .infestedCobblestone:                      return "minecraft:monster_egg"
            case .infestedStoneBrick:                       return "minecraft:monster_egg"
            case .infestedMossyStoneBrick:                  return "minecraft:monster_egg"
            case .infestedCrackedStoneBrick:                return "minecraft:monster_egg"
            case .infestedChiseledStoneBrick:               return "minecraft:monster_egg"
            case .infestedDeepslate:                        return "minecraft:infested_deepslate"
            case .turtleEgg:                                return "minecraft:turtle_egg"
            case .snifferEgg:                               return "minecraft:sniffer_egg"
            case .frogSpawn:                                return "minecraft:frog_spawn"

            case .ochreFroglight:                           return "minecraft:ochre_froglight"
            case .verdantFroglight:                         return "minecraft:verdant_froglight"
            case .pearlescentFroglight:                     return "minecraft:pearlescent_froglight"
            case .sponge:                                   return "minecraft:sponge"

            // Plants
            case .cactus:                                   return "minecraft:cactus"
            case .reeds:                                    return "minecraft:reeds"
            case .wheat:                                    return "minecraft:wheat"
            case .pumpkinStem:                              return "minecraft:pumpkin_stem"
            case .melonStem:                                return "minecraft:melon_stem"
            case .beetroot:                                 return "minecraft:beetroot"
            case .cocoa:                                    return "minecraft:cocoa"
            case .vine:                                     return "minecraft:vine"
            case .torchflowerCrop:                          return "minecraft:torchflower_crop"
            case .pitcherCrop:                              return "minecraft:pitcher_crop"
            case .potatoes:                                 return "minecraft:potatoes"
            case .carrots:                                  return "minecraft:carrots"
            case .melonBlock:                               return "minecraft:melon_block"
            case .pumpkin:                                  return "minecraft:pumpkin"
            case .carvedPumpkin:                            return "minecraft:carved_pumpkin"
            case .litPumpkin:                               return "minecraft:lit_pumpkin"
            case .sweetBerryBush:                           return "minecraft:sweet_berry_bush"
            case .caveVines:                                return "minecraft:cave_vines"
            case .caveVinesHeadWithBerries:                 return "minecraft:cave_vines_head_with_berries"
            case .caveVinesBodyWithBerries:                 return "minecraft:cave_vines_body_with_berries"
            case .bamboo:                                   return "minecraft:bamboo"
            case .brownMushroom:                            return "minecraft:brown_mushroom"
            case .redMushroom:                              return "minecraft:red_mushroom"

            case .brownMushroomBlock:                       return "minecraft:brown_mushroom_block"
            case .redMushroomBlock:                         return "minecraft:red_mushroom_block"

            case .deadbush:                                 return "minecraft:deadbush"
            case .tallgrass:                                return "minecraft:tallgrass"
            case .doublePlant:                              return "minecraft:double_plant"
            case .yellowFlower:                             return "minecraft:yellow_flower"
            case .redFlower:                                return "minecraft:red_flower"
            case .pitcherPlant:                             return "minecraft:pitcher_plant"
            case .pinkPetals:                               return "minecraft:pink_petals"
            case .witherRose:                               return "minecraft:wither_rose"
            case .torchflower:                              return "minecraft:torchflower"

            case .waterlily:                                return "minecraft:waterlily"
            case .seagrass:                                 return "minecraft:seagrass"
            case .kelp:                                     return "minecraft:kelp"
            case .driedKelpBlock:                           return "minecraft:dried_kelp_block"

            // Ocean Biome
            case .bubbleColumn:                             return "minecraft:bubble_column"
            case .seaPickle:                                return "minecraft:sea_pickle"
            case .seaLantern:                               return "minecraft:sea_lantern"
            case .conduit:                                  return "minecraft:conduit"

            // Snow Biome
            case .snow:                                     return "minecraft:snow"
            case .snowLayer:                                return "minecraft:snow_layer"
            case .powderSnow:                               return "minecraft:powder_snow"
            case .ice:                                      return "minecraft:ice"
            case .blueIce:                                  return "minecraft:blue_ice"
            case .packedIce:                                return "minecraft:packed_ice"
            case .frostedIce:                               return "minecraft:frosted_ice"

            // Caves & Cliffs
            case .glowLichen:                               return "minecraft:glow_lichen"
            case .dripstoneBlock:                           return "minecraft:dripstone_block"
            case .pointedDripstone:                         return "minecraft:pointed_dripstone"
            case .mossBlock:                                return "minecraft:moss_block"
            case .mossCarpet:                               return "minecraft:moss_carpet"
            case .dirtWithRoots:                            return "minecraft:dirt_with_roots"
            case .hangingRoots:                             return "minecraft:hanging_roots"
            case .bigDripleaf:                              return "minecraft:big_dripleaf"
            case .smallDripleafBlock:                       return "minecraft:small_dripleaf_block"
            case .sporeBlossom:                             return "minecraft:spore_blossom"
            case .azalea:                                   return "minecraft:azalea"
            case .floweringAzalea:                          return "minecraft:flowering_azalea"
            case .amethystBlock:                            return "minecraft:amethyst_block"
            case .buddingAmethyst:                          return "minecraft:budding_amethyst"
            case .amethystCluster:                          return "minecraft:amethyst_cluster"
            case .largeAmethystBud:                         return "minecraft:large_amethyst_bud"
            case .mediumAmethystBud:                        return "minecraft:medium_amethyst_bud"
            case .smallAmethystBud:                         return "minecraft:small_amethyst_bud"
            case .tuff:                                     return "minecraft:tuff"
            case .calcite:                                  return "minecraft:calcite"

            // Mangrove Swamp Biome
            case .mud:                                      return "minecraft:mud"
            case .muddyMangroveRoots:                       return "minecraft:muddy_mangrove_roots"
            case .mangroveRoots:                            return "minecraft:mangrove_roots"

            // Deep Dark Biome
            case .reinforcedDeepslate:                      return "minecraft:reinforced_deepslate"
            case .sculkSensor:                              return "minecraft:sculk_sensor"
            case .sculk:                                    return "minecraft:sculk"
            case .sculkVein:                                return "minecraft:sculk_vein"
            case .sculkCatalyst:                            return "minecraft:sculk_catalyst"
            case .sculkShrieker:                            return "minecraft:sculk_shrieker"
            case .calibratedSculkSensor:                    return "minecraft:calibrated_sculk_sensor"

            /* ---------- ---------- ---------- The Nether ---------- ---------- ---------- */
            case .netherrack:                               return "minecraft:netherrack"
            case .shroomlight:                              return "minecraft:shroomlight"
            case .netherWartBlock:                          return "minecraft:nether_wart_block"
            case .crimsonNylium:                            return "minecraft:crimson_nylium"
            case .warpedWartBlock:                          return "minecraft:warped_wart_block"
            case .warpedNylium:                             return "minecraft:warped_nylium"

            case .basalt:                                   return "minecraft:basalt"
            case .polishedBasalt:                           return "minecraft:polished_basalt"
            case .smoothBasalt:                             return "minecraft:smooth_basalt"
            case .soulSoil:                                 return "minecraft:soul_soil"
            case .soulSand:                                 return "minecraft:soul_sand"

            case .portal:                                   return "minecraft:portal"
            case .soulFire:                                 return "minecraft:soul_fire"
            case .magma:                                    return "minecraft:magma"
            case .glowstone:                                return "minecraft:glowstone"

            // Plants
            case .netherWart:                               return "minecraft:nether_wart"
            case .crimsonRoots:                             return "minecraft:crimson_roots"
            case .warpedRoots:                              return "minecraft:warped_roots"
            case .netherSprouts:                            return "minecraft:nether_sprouts"
            case .weepingVines:                             return "minecraft:weeping_vines"
            case .twistingVines:                            return "minecraft:twisting_vines"
            case .crimsonFungus:                            return "minecraft:crimson_fungus"
            case .warpedFungus:                             return "minecraft:warped_fungus"

            /* ---------- ---------- ---------- The End ---------- ---------- ---------- */
            case .endStone:                                 return "minecraft:end_stone"
            case .dragonEgg:                                return "minecraft:dragon_egg"
            case .chorusPlant:                              return "minecraft:chorus_plant"
            case .chorusFlower:                             return "minecraft:chorus_flower"

            case .endPortalFrame:                           return "minecraft:end_portal_frame"
            case .endPortal:                                return "minecraft:end_portal"
            case .endGateway:                               return "minecraft:end_gateway"

            /* ---------- ---------- ---------- Ores & Ore Blocks ---------- ---------- ---------- */
            case .coalOre:                                  return "minecraft:coal_ore"
            case .copperOre:                                return "minecraft:copper_ore"
            case .ironOre:                                  return "minecraft:iron_ore"
            case .goldOre:                                  return "minecraft:gold_ore"
            case .diamondOre:                               return "minecraft:diamond_ore"
            case .lapisOre:                                 return "minecraft:lapis_ore"
            case .redstoneOre:                              return "minecraft:redstone_ore"
            case .litRedstoneOre:                           return "minecraft:lit_redstone_ore"
            case .emeraldOre:                               return "minecraft:emerald_ore"
            case .netherGoldOre:                            return "minecraft:nether_gold_ore"
            case .quartzOre:                                return "minecraft:quartz_ore"

            case .deepslateCoalOre:                         return "minecraft:deepslate_coal_ore"
            case .deepslateCopperOre:                       return "minecraft:deepslate_copper_ore"
            case .deepslateIronOre:                         return "minecraft:deepslate_iron_ore"
            case .deepslateGoldOre:                         return "minecraft:deepslate_gold_ore"
            case .deepslateDiamondOre:                      return "minecraft:deepslate_diamond_ore"
            case .deepslateLapisOre:                        return "minecraft:deepslate_lapis_ore"
            case .deepslateRedstoneOre:                     return "minecraft:deepslate_redstone_ore"
            case .litDeepslateRedstoneOre:                  return "minecraft:lit_deepslate_redstone_ore"
            case .deepslateEmeraldOre:                      return "minecraft:deepslate_emerald_ore"

            case .rawCopperBlock:                           return "minecraft:raw_copper_block"
            case .rawIronBlock:                             return "minecraft:raw_iron_block"
            case .rawGoldBlock:                             return "minecraft:raw_gold_block"

            case .coalBlock:                                return "minecraft:coal_block"
            case .ironBlock:                                return "minecraft:iron_block"
            case .goldBlock:                                return "minecraft:gold_block"
            case .diamondBlock:                             return "minecraft:diamond_block"
            case .lapisBlock:                               return "minecraft:lapis_block"
            case .redstoneBlock:                            return "minecraft:redstone_block"
            case .emeraldBlock:                             return "minecraft:emerald_block"
            case .netheriteBlock:                           return "minecraft:netherite_block"
            case .ancientDebris:                            return "minecraft:ancient_debris"

            case .copperBlock:                              return "minecraft:copper_block"
            case .exposedCopper:                            return "minecraft:exposed_copper"
            case .oxidizedCopper:                           return "minecraft:oxidized_copper"
            case .weatheredCopper:                          return "minecraft:weathered_copper"

            case .cutCopper:                                return "minecraft:cut_copper"
            case .exposedCutCopper:                         return "minecraft:exposed_cut_copper"
            case .oxidizedCutCopper:                        return "minecraft:oxidized_cut_copper"
            case .weatheredCutCopper:                       return "minecraft:weathered_cut_copper"

            case .waxedCopper:                              return "minecraft:waxed_copper"
            case .waxedExposedCopper:                       return "minecraft:waxed_exposed_copper"
            case .waxedOxidizedCopper:                      return "minecraft:waxed_oxidized_copper"
            case .waxedWeatheredCopper:                     return "minecraft:waxed_weathered_copper"

            case .waxedCutCopper:                           return "minecraft:waxed_cut_copper"
            case .waxedExposedCutCopper:                    return "minecraft:waxed_exposed_cut_copper"
            case .waxedOxidizedCutCopper:                   return "minecraft:waxed_oxidized_cut_copper"
            case .waxedWeatheredCutCopper:                  return "minecraft:waxed_weathered_cut_copper"

            /* ---------- ---------- ---------- Stones ---------- ---------- ---------- */
            case .boneBlock:                                return "minecraft:bone_block"
            case .cobblestone:                              return "minecraft:cobblestone"
            case .mossyCobblestone:                         return "minecraft:mossy_cobblestone"
            case .cobbledDeepslate:                         return "minecraft:cobbled_deepslate"

            case .stone:                                    return "minecraft:stone"
            case .granite:                                  return "minecraft:stone"
            case .diorite:                                  return "minecraft:stone"
            case .andesite:                                 return "minecraft:stone"
            case .polishedGranite:                          return "minecraft:stone"
            case .polishedDiorite:                          return "minecraft:stone"
            case .polishedAndesite:                         return "minecraft:stone"

            case .stonebricks:                              return "minecraft:stonebrick"
            case .mossyStoneBricks:                         return "minecraft:stonebrick"
            case .crackedStoneBricks:                       return "minecraft:stonebrick"
            case .chiseledStoneBricks:                      return "minecraft:stonebrick"
            case .smoothStoneBricks:                        return "minecraft:stonebrick"

            case .blackstone:                               return "minecraft:blackstone"
            case .polishedBlackstone:                       return "minecraft:polished_blackstone"

            case .deepslate:                                return "minecraft:deepslate"
            case .polishedDeepslate:                        return "minecraft:polished_deepslate"

            case .polishedBlackstoneBricks:                 return "minecraft:polished_blackstone_bricks"
            case .crackedPolishedBlackstoneBricks:          return "minecraft:cracked_polished_blackstone_bricks"
            case .chiseledPolishedBlackstone:               return "minecraft:chiseled_polished_blackstone"
            case .gildedBlackstone:                         return "minecraft:gilded_blackstone"

            case .deepslateTiles:                           return "minecraft:deepslate_tiles"
            case .crackedDeepslateTiles:                    return "minecraft:cracked_deepslate_tiles"
            case .deepslateBricks:                          return "minecraft:deepslate_bricks"
            case .crackedDeepslateBricks:                   return "minecraft:cracked_deepslate_bricks"
            case .chiseledDeepslate:                        return "minecraft:chiseled_deepslate"

            case .smoothStone:                              return "minecraft:smooth_stone"
            case .redBrickBlock:                            return "minecraft:brick_block"
            case .packedMud:                                return "minecraft:packed_mud"
            case .mudBricks:                                return "minecraft:mud_bricks"

            case .netherBrick:                              return "minecraft:nether_brick"
            case .redNetherBrick:                           return "minecraft:red_nether_brick"
            case .chiseledNetherBricks:                     return "minecraft:chiseled_nether_bricks"
            case .crackedNetherBricks:                      return "minecraft:cracked_nether_bricks"
            case .endBricks:                                return "minecraft:end_bricks"

            case .prismarine:                               return "minecraft:prismarine"
            case .darkPrismarine:                           return "minecraft:prismarine"
            case .prismarineBricks:                         return "minecraft:prismarine"

            case .quartzBricks:                             return "minecraft:quartz_bricks"
            case .quartzBlock:                              return "minecraft:quartz_block"
            case .pillarQuartzBlock:                        return "minecraft:quartz_block"
            case .chiseledQuartzBlock:                      return "minecraft:quartz_block"
            case .smoothQuartzBlock:                        return "minecraft:quartz_block"

            case .purpurBlock:                              return "minecraft:purple_block"
            case .pillarPurpurBlock:                        return "minecraft:purple_block"
            case .chiseledPurpurBlock:                      return "minecraft:purple_block"
            case .smoothPurpurBlock:                        return "minecraft:purple_block"

            case .sandstone:                                return "minecraft:sandstone"
            case .chiseledSandstone:                        return "minecraft:sandstone"
            case .cutSandstone:                             return "minecraft:sandstone"
            case .smoothSandstone:                          return "minecraft:sandstone"
            case .redSandstone:                             return "minecraft:red_sandstone"
            case .chiseledRedSandstone:                     return "minecraft:red_sandstone"
            case .cutRedSandstone:                          return "minecraft:red_sandstone"
            case .smoothRedSandstone:                       return "minecraft:red_sandstone"

            /* ---------- ---------- ---------- Trees ---------- ---------- ---------- */
            case .oakLog:                                   return "minecraft:oak_log"
            case .spruceLog:                                return "minecraft:spruce_log"
            case .birchLog:                                 return "minecraft:birch_log"
            case .jungleLog:                                return "minecraft:jungle_log"
            case .acaciaLog:                                return "minecraft:acacia_log"
            case .darkOakLog:                               return "minecraft:dark_oak_log"
            case .mangroveLog:                              return "minecraft:mangrove_log"
            case .cherryLog:                                return "minecraft:cherry_log"
            case .crimsonStem:                              return "minecraft:crimson_stem"
            case .warpedStem:                               return "minecraft:warped_stem"

            case .strippedOakLog:                           return "minecraft:stripped_oak_log"
            case .strippedSpruceLog:                        return "minecraft:stripped_spruce_log"
            case .strippedBirchLog:                         return "minecraft:stripped_birch_log"
            case .strippedJungleLog:                        return "minecraft:stripped_jungle_log"
            case .strippedAcaciaLog:                        return "minecraft:stripped_acacia_log"
            case .strippedDarkOakLog:                       return "minecraft:stripped_dark_oak_log"
            case .strippedMangroveLog:                      return "minecraft:stripped_mangrove_log"
            case .strippedCherryLog:                        return "minecraft:stripped_cherry_log"
            case .strippedCrimsonStem:                      return "minecraft:stripped_crimson_stem"
            case .strippedWarpedStem:                       return "minecraft:stripped_warped_stem"

            case .oakWood:                                  return "minecraft:wood"
            case .spruceWood:                               return "minecraft:wood"
            case .birchWood:                                return "minecraft:wood"
            case .jungleWood:                               return "minecraft:wood"
            case .acaciaWood:                               return "minecraft:wood"
            case .darkOakWood:                              return "minecraft:wood"
            case .mangroveWood:                             return "minecraft:mangrove_wood"
            case .cherryWood:                               return "minecraft:cherry_wood"
            case .bambooBlock:                              return "minecraft:bamboo_block"
            case .crimsonHyphae:                            return "minecraft:crimson_hyphae"
            case .warpedHyphae:                             return "minecraft:warped_hyphae"

            case .strippedOakWood:                          return "minecraft:wood"
            case .strippedSpruceWood:                       return "minecraft:wood"
            case .strippedBirchWood:                        return "minecraft:wood"
            case .strippedJungleWood:                       return "minecraft:wood"
            case .strippedAcaciaWood:                       return "minecraft:wood"
            case .strippedDarkOakWood:                      return "minecraft:wood"
            case .strippedMangroveWood:                     return "minecraft:stripped_mangrove_wood"
            case .strippedCherryWood:                       return "minecraft:stripped_cherry_wood"
            case .strippedBambooBlock:                      return "minecraft:stripped_bamboo_block"
            case .strippedCrimsonHyphae:                    return "minecraft:stripped_crimson_hyphae"
            case .strippedWarpedHyphae:                     return "minecraft:stripped_warped_hyphae"

            case .oakPlanks:                                return "minecraft:planks"
            case .sprucePlanks:                             return "minecraft:planks"
            case .birchPlanks:                              return "minecraft:planks"
            case .junglePlanks:                             return "minecraft:planks"
            case .acaciaPlanks:                             return "minecraft:planks"
            case .darkOakPlanks:                            return "minecraft:planks"
            case .mangrovePlanks:                           return "minecraft:mangrove_planks"
            case .cherryPlanks:                             return "minecraft:cherry_planks"
            case .bambooPlanks:                             return "minecraft:bamboo_planks"
            case .bambooMosaic:                             return "minecraft:bamboo_mosaic"
            case .crimsonPlanks:                            return "minecraft:crimson_planks"
            case .warpedPlanks:                             return "minecraft:warped_planks"

            case .oakLeaves:                                return "minecraft:leaves"
            case .spruceLeaves:                             return "minecraft:leaves"
            case .birchLeaves:                              return "minecraft:leaves"
            case .jungleLeaves:                             return "minecraft:leaves"
            case .acaciaLeaves:                             return "minecraft:leaves2"
            case .darkOakLeaves:                            return "minecraft:leaves2"
            case .mangroveLeaves:                           return "minecraft:mangrove_leaves"
            case .cherryLeaves:                             return "minecraft:cherry_leaves"
            case .azaleaLeaves:                             return "minecraft:azalea_leaves"
            case .azaleaLeavesFlowered:                     return "minecraft:azalea_leaves_flowered"

            case .oakSapling:                               return "minecraft:sapling"
            case .spruceSapling:                            return "minecraft:sapling"
            case .birchSapling:                             return "minecraft:sapling"
            case .jungleSapling:                            return "minecraft:sapling"
            case .acaciaSapling:                            return "minecraft:sapling"
            case .darkOakSapling:                           return "minecraft:sapling"
            case .mangrovePropagule:                        return "minecraft:mangrove_propagule"
            case .cherrySapling:                            return "minecraft:cherry_sapling"
            case .bambooSapling:                            return "minecraft:bamboo_sapling"

            /* ---------- ---------- ---------- Fences & Gates ---------- ---------- ---------- */
            case .oakFence:                                 return "minecraft:oak_fence"
            case .spruceFence:                              return "minecraft:spruce_fence"
            case .birchFence:                               return "minecraft:birch_fence"
            case .jungleFence:                              return "minecraft:jungle_fence"
            case .acaciaFence:                              return "minecraft:acacia_fence"
            case .darkOakFence:                             return "minecraft:dark_oak_fence"
            case .mangroveFence:                            return "minecraft:mangrove_fence"
            case .cherryFence:                              return "minecraft:cherry_fence"
            case .bambooFence:                              return "minecraft:bamboo_fence"
            case .crimsonFence:                             return "minecraft:crimson_fence"
            case .warpedFence:                              return "minecraft:warped_fence"
            case .netherBrickFence:                         return "minecraft:nether_brick_fence"

            case .oakFenceGate:                             return "minecraft:fence_gate"
            case .spruceFenceGate:                          return "minecraft:spruce_fence_gate"
            case .birchFenceGate:                           return "minecraft:birch_fence_gate"
            case .jungleFenceGate:                          return "minecraft:jungle_fence_gate"
            case .acaciaFenceGate:                          return "minecraft:acacia_fence_gate"
            case .darkOakFenceGate:                         return "minecraft:dark_oak_fence_gate"
            case .mangroveFenceGate:                        return "minecraft:mangrove_fence_gate"
            case .cherryFenceGate:                          return "minecraft:cherry_fence_gate"
            case .bambooFenceGate:                          return "minecraft:bamboo_fence_gate"
            case .crimsonFenceGate:                         return "minecraft:crimson_fence_gate"
            case .warpedFenceGate:                          return "minecraft:warped_fence_gate"

            /* ---------- ---------- ---------- Walls ---------- ---------- ---------- */
            case .cobblestoneWall:                          return "minecraft:cobblestone_wall"
            case .mossyCobblestoneWall:                     return "minecraft:cobblestone_wall"
            case .graniteWall:                              return "minecraft:cobblestone_wall"
            case .dioriteWall:                              return "minecraft:cobblestone_wall"
            case .andesiteWall:                             return "minecraft:cobblestone_wall"
            case .sandstoneWall:                            return "minecraft:cobblestone_wall"
            case .redSandstoneWall:                         return "minecraft:cobblestone_wall"
            case .stoneBrickWall:                           return "minecraft:cobblestone_wall"
            case .mossyStoneBrickWall:                      return "minecraft:cobblestone_wall"
            case .redBrickWall:                             return "minecraft:cobblestone_wall"
            case .netherBrickWall:                          return "minecraft:cobblestone_wall"
            case .redNetherBrickWall:                       return "minecraft:cobblestone_wall"
            case .endBrickWall:                             return "minecraft:cobblestone_wall"
            case .prismarineWall:                           return "minecraft:cobblestone_wall"

            case .blackstoneWall:                           return "minecraft:blackstone_wall"
            case .polishedBlackstoneWall:                   return "minecraft:polished_blackstone_wall"
            case .polishedBlackstoneBrickWall:              return "minecraft:polished_blackstone_brick_wall"

            case .cobbledDeepslateWall:                     return "minecraft:cobbled_deepslate_wall"
            case .deepslateTileWall:                        return "minecraft:deepslate_tile_wall"
            case .polishedDeepslateWall:                    return "minecraft:polished_deepslate_wall"
            case .deepslateBrickWall:                       return "minecraft:deepslate_brick_wall"

            case .mudBrickWall:                             return "minecraft:mud_brick_wall"

            /* ---------- ---------- ---------- Stairs ---------- ---------- ---------- */
            case .oakStairs:                                return "minecraft:oak_stairs"
            case .spruceStairs:                             return "minecraft:spruce_stairs"
            case .birchStairs:                              return "minecraft:birch_stairs"
            case .jungleStairs:                             return "minecraft:jungle_stairs"
            case .acaciaStairs:                             return "minecraft:acacia_stairs"
            case .darkOakStairs:                            return "minecraft:dark_oak_stairs"
            case .mangroveStairs:                           return "minecraft:mangrove_stairs"
            case .cherryStairs:                             return "minecraft:cherry_stairs"
            case .bambooStairs:                             return "minecraft:bamboo_stairs"
            case .bambooMosaicStairs:                       return "minecraft:bamboo_mosaic_stairs"
            case .crimsonStairs:                            return "minecraft:crimson_stairs"
            case .warpedStairs:                             return "minecraft:warped_stairs"

            case .normalStoneStairs:                        return "minecraft:normal_stone_stairs"
            case .cobblestoneStairs:                        return "minecraft:stone_stairs"
            case .mossyStoneBrickStairs:                    return "minecraft:mossy_stone_brick_stairs"
            case .stoneBrickStairs:                         return "minecraft:stone_brick_stairs"
            case .mossyCobblestoneStairs:                   return "minecraft:mossy_cobblestone_stairs"

            case .graniteStairs:                            return "minecraft:granite_stairs"
            case .dioriteStairs:                            return "minecraft:diorite_stairs"
            case .andesiteStairs:                           return "minecraft:andesite_stairs"
            case .polishedGraniteStairs:                    return "minecraft:polished_granite_stairs"
            case .polishedDioriteStairs:                    return "minecraft:polished_diorite_stairs"
            case .polishedAndesiteStairs:                   return "minecraft:polished_andesite_stairs"

            case .sandstoneStairs:                          return "minecraft:sandstone_stairs"
            case .redSandstoneStairs:                       return "minecraft:red_sandstone_stairs"
            case .smoothSandstoneStairs:                    return "minecraft:smooth_sandstone_stairs"
            case .smoothRedSandstoneStairs:                 return "minecraft:smooth_red_sandstone_stairs"
            case .redBrickStairs:                           return "minecraft:brick_stairs"
            case .mudBrickStairs:                           return "minecraft:mud_brick_stairs"

            case .blackstoneStairs:                         return "minecraft:blackstone_stairs"
            case .polishedBlackstoneStairs:                 return "minecraft:polished_blackstone_stairs"
            case .polishedBlackstoneBrickStairs:            return "minecraft:polished_blackstone_brick_stairs"

            case .cobbledDeepslateStairs:                   return "minecraft:cobbled_deepslate_stairs"
            case .deepslateTileStairs:                      return "minecraft:deepslate_tile_stairs"
            case .polishedDeepslateStairs:                  return "minecraft:polished_deepslate_stairs"
            case .deepslateBrickStairs:                     return "minecraft:deepslate_brick_stairs"

            case .netherBrickStairs:                        return "minecraft:nether_brick_stairs"
            case .redNetherBrickStairs:                     return "minecraft:red_nether_brick_stairs"
            case .endBrickStairs:                           return "minecraft:end_brick_stairs"
            case .quartzStairs:                             return "minecraft:quartz_stairs"
            case .smoothQuartzStairs:                       return "minecraft:smooth_quartz_stairs"
            case .purpurStairs:                             return "minecraft:purple_stairs"
            case .prismarineStairs:                         return "minecraft:prismarine_stairs"
            case .darkPrismarineStairs:                     return "minecraft:dark_prismarine_stairs"
            case .prismarineBricksStairs:                   return "minecraft:prismarine_bricks_stairs"

            case .cutCopperStairs:                          return "minecraft:cut_copper_stairs"
            case .exposedCutCopperStairs:                   return "minecraft:exposed_cut_copper_stairs"
            case .oxidizedCutCopperStairs:                  return "minecraft:oxidized_cut_copper_stairs"
            case .weatheredCutCopperStairs:                 return "minecraft:weathered_cut_copper_stairs"
            case .waxedCutCopperStairs:                     return "minecraft:waxed_cut_copper_stairs"
            case .waxedExposedCutCopperStairs:              return "minecraft:waxed_exposed_cut_copper_stairs"
            case .waxedOxidizedCutCopperStairs:             return "minecraft:waxed_oxidized_cut_copper_stairs"
            case .waxedWeatheredCutCopperStairs:            return "minecraft:waxed_weathered_cut_copper_stairs"

            /* ---------- ---------- ---------- Slabs ---------- ---------- ---------- */
            case .oakSlab:                                  return "minecraft:wooden_slab"
            case .spruceSlab:                               return "minecraft:wooden_slab"
            case .birchSlab:                                return "minecraft:wooden_slab"
            case .jungleSlab:                               return "minecraft:wooden_slab"
            case .acaciaSlab:                               return "minecraft:wooden_slab"
            case .darkOakSlab:                              return "minecraft:wooden_slab"
            case .mangroveSlab:                             return "minecraft:mangrove_slab"
            case .cherrySlab:                               return "minecraft:cherry_slab"
            case .bambooSlab:                               return "minecraft:bamboo_slab"
            case .bambooMosaicSlab:                         return "minecraft:bamboo_mosaic_slab"
            case .crimsonSlab:                              return "minecraft:crimson_slab"
            case .warpedSlab:                               return "minecraft:warped_slab"

            case .oakDoubleSlab:                            return "minecraft:double_wooden_slab"
            case .spruceDoubleSlab:                         return "minecraft:double_wooden_slab"
            case .birchDoubleSlab:                          return "minecraft:double_wooden_slab"
            case .jungleDoubleSlab:                         return "minecraft:double_wooden_slab"
            case .acaciaDoubleSlab:                         return "minecraft:double_wooden_slab"
            case .darkOakDoubleSlab:                        return "minecraft:double_wooden_slab"
            case .mangroveDoubleSlab:                       return "minecraft:mangrove_double_slab"
            case .cherryDoubleSlab:                         return "minecraft:cherry_double_slab"
            case .bambooDoubleSlab:                         return "minecraft:bamboo_double_slab"
            case .bambooMosaicDoubleSlab:                   return "minecraft:bamboo_mosaic_double_slab"
            case .crimsonDoubleSlab:                        return "minecraft:crimson_double_slab"
            case .warpedDoubleSlab:                         return "minecraft:warped_double_slab"

            case .smoothStoneSlab:                          return "minecraft:stone_block_slab"
            case .cobblestoneSlab:                          return "minecraft:stone_block_slab"
            case .stoneBrickSlab:                           return "minecraft:stone_block_slab"
            case .sandstoneSlab:                            return "minecraft:stone_block_slab"
            case .redBrickSlab:                             return "minecraft:stone_block_slab"
            case .netherBrickSlab:                          return "minecraft:stone_block_slab"
            case .quartzSlab:                               return "minecraft:stone_block_slab"
            case .smoothStoneDoubleSlab:                    return "minecraft:double_stone_block_slab"
            case .cobblestoneDoubleSlab:                    return "minecraft:double_stone_block_slab"
            case .stoneBrickDoubleSlab:                     return "minecraft:double_stone_block_slab"
            case .sandstoneDoubleSlab:                      return "minecraft:double_stone_block_slab"
            case .redBrickDoubleSlab:                       return "minecraft:double_stone_block_slab"
            case .netherBrickDoubleSlab:                    return "minecraft:double_stone_block_slab"
            case .quartzDoubleSlab:                         return "minecraft:double_stone_block_slab"

            case .mossyCobblestoneSlab:                     return "minecraft:stone_block_slab2"
            case .smoothSandstoneSlab:                      return "minecraft:stone_block_slab2"
            case .redSandstoneSlab:                         return "minecraft:stone_block_slab2"
            case .redNetherBrickSlab:                       return "minecraft:stone_block_slab2"
            case .purpurSlab:                               return "minecraft:stone_block_slab2"
            case .prismarineRoughSlab:                      return "minecraft:stone_block_slab2"
            case .prismarineDarkSlab:                       return "minecraft:stone_block_slab2"
            case .prismarineBrickSlab:                      return "minecraft:stone_block_slab2"
            case .mossyCobblestoneDoubleSlab:               return "minecraft:double_stone_block_slab2"
            case .smoothSandstoneDoubleSlab:                return "minecraft:double_stone_block_slab2"
            case .redSandstoneDoubleSlab:                   return "minecraft:double_stone_block_slab2"
            case .redNetherBrickDoubleSlab:                 return "minecraft:double_stone_block_slab2"
            case .purpurDoubleSlab:                         return "minecraft:double_stone_block_slab2"
            case .prismarineRoughDoubleSlab:                return "minecraft:double_stone_block_slab2"
            case .prismarineDarkDoubleSlab:                 return "minecraft:double_stone_block_slab2"
            case .prismarineBrickDoubleSlab:                return "minecraft:double_stone_block_slab2"

            case .smoothRedSandstoneSlab:                   return "minecraft:stone_block_slab3"
            case .graniteSlab:                              return "minecraft:stone_block_slab3"
            case .dioriteSlab:                              return "minecraft:stone_block_slab3"
            case .andesiteSlab:                             return "minecraft:stone_block_slab3"
            case .polishedGraniteSlab:                      return "minecraft:stone_block_slab3"
            case .polishedDioriteSlab:                      return "minecraft:stone_block_slab3"
            case .polishedAndesiteSlab:                     return "minecraft:stone_block_slab3"
            case .endStoneBrickSlab:                        return "minecraft:stone_block_slab3"
            case .smoothRedSandstoneDoubleSlab:             return "minecraft:double_stone_block_slab3"
            case .graniteDoubleSlab:                        return "minecraft:double_stone_block_slab3"
            case .dioriteDoubleSlab:                        return "minecraft:double_stone_block_slab3"
            case .andesiteDoubleSlab:                       return "minecraft:double_stone_block_slab3"
            case .polishedGraniteDoubleSlab:                return "minecraft:double_stone_block_slab3"
            case .polishedDioriteDoubleSlab:                return "minecraft:double_stone_block_slab3"
            case .polishedAndesiteDoubleSlab:               return "minecraft:double_stone_block_slab3"
            case .endStoneBrickDoubleSlab:                  return "minecraft:double_stone_block_slab3"

            case .stoneSlab:                                return "minecraft:stone_block_slab4"
            case .mossyStoneBrickSlab:                      return "minecraft:stone_block_slab4"
            case .cutSandstoneSlab:                         return "minecraft:stone_block_slab4"
            case .cutRedSandstoneSlab:                      return "minecraft:stone_block_slab4"
            case .smoothQuartzSlab:                         return "minecraft:stone_block_slab4"
            case .stoneDoubleSlab:                          return "minecraft:double_stone_block_slab4"
            case .mossyStoneBrickDoubleSlab:                return "minecraft:double_stone_block_slab4"
            case .cutSandstoneDoubleSlab:                   return "minecraft:double_stone_block_slab4"
            case .cutRedSandstoneDoubleSlab:                return "minecraft:double_stone_block_slab4"
            case .smoothQuartzDoubleSlab:                   return "minecraft:double_stone_block_slab4"

            case .blackstoneSlab:                           return "minecraft:blackstone_slab"
            case .polishedBlackstoneSlab:                   return "minecraft:polished_blackstone_slab"
            case .polishedBlackstoneBrickSlab:              return "minecraft:polished_blackstone_brick_slab"
            case .blackstoneDoubleSlab:                     return "minecraft:blackstone_double_slab"
            case .polishedBlackstoneDoubleSlab:             return "minecraft:polished_blackstone_double_slab"
            case .polishedBlackstoneBrickDoubleSlab:        return "minecraft:polished_blackstone_brick_double_slab"

            case .cobbledDeepslateSlab:                     return "minecraft:cobbled_deepslate_slab"
            case .deepslateTileSlab:                        return "minecraft:deepslate_tile_slab"
            case .polishedDeepslateSlab:                    return "minecraft:polished_deepslate_slab"
            case .deepslateBrickSlab:                       return "minecraft:deepslate_brick_slab"
            case .cobbledDeepslateDoubleSlab:               return "minecraft:cobbled_deepslate_double_slab"
            case .deepslateTileDoubleSlab:                  return "minecraft:deepslate_tile_double_slab"
            case .polishedDeepslateDoubleSlab:              return "minecraft:polished_deepslate_double_slab"
            case .deepslateBrickDoubleSlab:                 return "minecraft:deepslate_brick_double_slab"

            case .mudBrickSlab:                             return "minecraft:mud_brick_slab"
            case .mudBrickDoubleSlab:                       return "minecraft:mud_brick_double_slab"

            case .cutCopperSlab:                            return "minecraft:cut_copper_slab"
            case .exposedCutCopperSlab:                     return "minecraft:exposed_cut_copper_slab"
            case .oxidizedCutCopperSlab:                    return "minecraft:oxidized_cut_copper_slab"
            case .weatheredCutCopperSlab:                   return "minecraft:weathered_cut_copper_slab"
            case .waxedCutCopperSlab:                       return "minecraft:waxed_cut_copper_slab"
            case .waxedExposedCutCopperSlab:                return "minecraft:waxed_exposed_cut_copper_slab"
            case .waxedOxidizedCutCopperSlab:               return "minecraft:waxed_oxidized_cut_copper_slab"
            case .waxedWeatheredCutCopperSlab:              return "minecraft:waxed_weathered_cut_copper_slab"

            case .doubleCutCopperSlab:                      return "minecraft:double_cut_copper_slab"
            case .exposedDoubleCutCopperSlab:               return "minecraft:exposed_double_cut_copper_slab"
            case .oxidizedDoubleCutCopperSlab:              return "minecraft:oxidized_double_cut_copper_slab"
            case .weatheredDoubleCutCopperSlab:             return "minecraft:weathered_double_cut_copper_slab"
            case .waxedDoubleCutCopperSlab:                 return "minecraft:waxed_double_cut_copper_slab"
            case .waxedExposedDoubleCutCopperSlab:          return "minecraft:waxed_exposed_double_cut_copper_slab"
            case .waxedOxidizedDoubleCutCopperSlab:         return "minecraft:waxed_oxidized_double_cut_copper_slab"
            case .waxedWeatheredDoubleCutCopperSlab:        return "minecraft:waxed_weathered_double_cut_copper_slab"

            /* ---------- ---------- ---------- Signs ---------- ---------- ---------- */
            case .oakStandingSign:                          return "minecraft:standing_sign"
            case .spruceStandingSign:                       return "minecraft:spruce_standing_sign"
            case .birchStandingSign:                        return "minecraft:birch_standing_sign"
            case .acaciaStandingSign:                       return "minecraft:acacia_standing_sign"
            case .jungleStandingSign:                       return "minecraft:jungle_standing_sign"
            case .darkoakStandingSign:                      return "minecraft:darkoak_standing_sign"
            case .mangroveStandingSign:                     return "minecraft:mangrove_standing_sign"
            case .cherryStandingSign:                       return "minecraft:cherry_standing_sign"
            case .bambooStandingSign:                       return "minecraft:bamboo_standing_sign"
            case .crimsonStandingSign:                      return "minecraft:crimson_standing_sign"
            case .warpedStandingSign:                       return "minecraft:warped_standing_sign"

            case .oakHangingSign:                           return "minecraft:oak_hanging_sign"
            case .spruceHangingSign:                        return "minecraft:spruce_hanging_sign"
            case .birchHangingSign:                         return "minecraft:birch_hanging_sign"
            case .jungleHangingSign:                        return "minecraft:jungle_hanging_sign"
            case .acaciaHangingSign:                        return "minecraft:acacia_hanging_sign"
            case .darkOakHangingSign:                       return "minecraft:darkoak_hanging_sign"
            case .mangroveHangingSign:                      return "minecraft:mangrove_hanging_sign"
            case .cherryHangingSign:                        return "minecraft:cherry_hanging_sign"
            case .bambooHangingSign:                        return "minecraft:bamboo_hanging_sign"
            case .crimsonHangingSign:                       return "minecraft:crimson_hanging_sign"
            case .warpedHangingSign:                        return "minecraft:warped_hanging_sign"

            case .oakWallSign:                              return "minecraft:wall_sign"
            case .spruceWallSign:                           return "minecraft:spruce_wall_sign"
            case .birchWallSign:                            return "minecraft:birch_wall_sign"
            case .acaciaWallSign:                           return "minecraft:acacia_wall_sign"
            case .jungleWallSign:                           return "minecraft:jungle_wall_sign"
            case .darkoakWallSign:                          return "minecraft:darkoak_wall_sign"
            case .mangroveWallSign:                         return "minecraft:mangrove_wall_sign"
            case .cherryWallSign:                           return "minecraft:cherry_wall_sign"
            case .bambooWallSign:                           return "minecraft:bamboo_wall_sign"
            case .crimsonWallSign:                          return "minecraft:crimson_wall_sign"
            case .warpedWallSign:                           return "minecraft:warped_wall_sign"

            /* ---------- ---------- ---------- Doors & Trapdoors ---------- ---------- ---------- */
            case .oakDoor:                                  return "minecraft:wooden_door"
            case .spruceDoor:                               return "minecraft:spruce_door"
            case .birchDoor:                                return "minecraft:birch_door"
            case .jungleDoor:                               return "minecraft:jungle_door"
            case .acaciaDoor:                               return "minecraft:acacia_door"
            case .darkOakDoor:                              return "minecraft:dark_oak_door"
            case .mangroveDoor:                             return "minecraft:mangrove_door"
            case .cherryDoor:                               return "minecraft:cherry_door"
            case .bambooDoor:                               return "minecraft:bamboo_door"
            case .crimsonDoor:                              return "minecraft:crimson_door"
            case .warpedDoor:                               return "minecraft:warped_door"
            case .ironDoor:                                 return "minecraft:iron_door"

            case .oakTrapdoor:                              return "minecraft:trapdoor"
            case .spruceTrapdoor:                           return "minecraft:spruce_trapdoor"
            case .birchTrapdoor:                            return "minecraft:birch_trapdoor"
            case .jungleTrapdoor:                           return "minecraft:jungle_trapdoor"
            case .acaciaTrapdoor:                           return "minecraft:acacia_trapdoor"
            case .darkOakTrapdoor:                          return "minecraft:dark_oak_trapdoor"
            case .mangroveTrapdoor:                         return "minecraft:mangrove_trapdoor"
            case .cherryTrapdoor:                           return "minecraft:cherry_trapdoor"
            case .bambooTrapdoor:                           return "minecraft:bamboo_trapdoor"
            case .crimsonTrapdoor:                          return "minecraft:crimson_trapdoor"
            case .warpedTrapdoor:                           return "minecraft:warped_trapdoor"
            case .ironTrapdoor:                             return "minecraft:iron_trapdoor"

            /* ---------- ---------- ---------- Village Blocks ---------- ---------- ---------- */
            case .ironBars:                                 return "minecraft:iron_bars"
            case .ladder:                                   return "minecraft:ladder"
            case .scaffolding:                              return "minecraft:scaffolding"
            case .honeycombBlock:                           return "minecraft:honeycomb_block"
            case .lodestone:                                return "minecraft:lodestone"
            case .hayBlock:                                 return "minecraft:hay_block"

            case .torch:                                    return "minecraft:torch"
            case .soulTorch:                                return "minecraft:soul_torch"
            case .lantern:                                  return "minecraft:lantern"
            case .soulLantern:                              return "minecraft:soul_lantern"
            case .campfire:                                 return "minecraft:campfire"
            case .soulCampfire:                             return "minecraft:soul_campfire"

            case .craftingTable:                            return "minecraft:crafting_table"
            case .cartographyTable:                         return "minecraft:cartography_table"
            case .fletchingTable:                           return "minecraft:fletching_table"
            case .smithingTable:                            return "minecraft:smithing_table"
            case .beehive:                                  return "minecraft:beehive"
            case .furnace:                                  return "minecraft:furnace"
            case .litFurnace:                               return "minecraft:lit_furnace"
            case .blastFurnace:                             return "minecraft:blast_furnace"
            case .litBlastFurnace:                          return "minecraft:lit_blast_furnace"
            case .smoker:                                   return "minecraft:smoker"
            case .litSmoker:                                return "minecraft:lit_smoker"
            case .respawnAnchor:                            return "minecraft:respawn_anchor"
            case .brewingStand:                             return "minecraft:brewing_stand"
            case .anvil:                                    return "minecraft:anvil"
            case .grindstone:                               return "minecraft:grindstone"
            case .enchantingTable:                          return "minecraft:enchanting_table"
            case .bookshelf:                                return "minecraft:bookshelf"
            case .chiseledBookshelf:                        return "minecraft:chiseled_bookshelf"
            case .lectern:                                  return "minecraft:lectern"
            case .composter:                                return "minecraft:composter"

            case .emptyCauldron:                            return "minecraft:cauldron"
            case .waterCauldron:                            return "minecraft:cauldron"
            case .lavaCauldron:                             return "minecraft:cauldron"
            case .powerSnowCauldron:                        return "minecraft:cauldron"

            case .chest:                                    return "minecraft:chest"
            case .trappedChest:                             return "minecraft:trapped_chest"
            case .enderChest:                               return "minecraft:ender_chest"
            case .barrel:                                   return "minecraft:barrel"

            case .noteblock:                                return "minecraft:noteblock"
            case .jukebox:                                  return "minecraft:jukebox"
            case .frame:                                    return "minecraft:frame"
            case .glowFrame:                                return "minecraft:glow_frame"
            case .flowerPot:                                return "minecraft:flower_pot"
            case .beacon:                                   return "minecraft:beacon"
            case .bell:                                     return "minecraft:bell"
            case .stonecutterBlock:                         return "minecraft:stonecutter_block"
            case .loom:                                     return "minecraft:loom"
            case .decoratedPot:                             return "minecraft:decorated_pot"
            case .chain:                                    return "minecraft:chain"
            case .endRod:                                   return "minecraft:end_rod"
            case .lightningRod:                             return "minecraft:lightning_rod"

            case .skull:                                    return "minecraft:skull"
            case .rail:                                     return "minecraft:rail"
            case .goldenRail:                               return "minecraft:golden_rail"
            case .detectorRail:                             return "minecraft:detector_rail"
            case .activatorRail:                            return "minecraft:activator_rail"

            /* ---------- ---------- ---------- Tech Blocks ---------- ---------- ---------- */
            case .commandBlock:                             return "minecraft:command_block"
            case .repeatingCommandBlock:                    return "minecraft:repeating_command_block"
            case .chainCommandBlock:                        return "minecraft:chain_command_block"
            case .structureBlock:                           return "minecraft:structure_block"
            case .structureVoid:                            return "minecraft:structure_void"
            case .movingBlock:                              return "minecraft:moving_block"
            case .lightBlock:                               return "minecraft:light_block"
            case .barrier:                                  return "minecraft:barrier"
            case .jigsaw:                                   return "minecraft:jigsaw"

            case .woodenButton:                             return "minecraft:wooden_button"
            case .spruceButton:                             return "minecraft:spruce_button"
            case .birchButton:                              return "minecraft:birch_button"
            case .jungleButton:                             return "minecraft:jungle_button"
            case .acaciaButton:                             return "minecraft:acacia_button"
            case .darkOakButton:                            return "minecraft:dark_oak_button"
            case .mangroveButton:                           return "minecraft:mangrove_button"
            case .cherryButton:                             return "minecraft:cherry_button"
            case .bambooButton:                             return "minecraft:bamboo_button"
            case .crimsonButton:                            return "minecraft:crimson_button"
            case .warpedButton:                             return "minecraft:warped_button"
            case .stoneButton:                              return "minecraft:stone_button"
            case .polishedBlackstoneButton:                 return "minecraft:polished_blackstone_button"

            case .woodenPressurePlate:                      return "minecraft:wooden_pressure_plate"
            case .sprucePressurePlate:                      return "minecraft:spruce_pressure_plate"
            case .birchPressurePlate:                       return "minecraft:birch_pressure_plate"
            case .junglePressurePlate:                      return "minecraft:jungle_pressure_plate"
            case .acaciaPressurePlate:                      return "minecraft:acacia_pressure_plate"
            case .darkOakPressurePlate:                     return "minecraft:dark_oak_pressure_plate"
            case .mangrovePressurePlate:                    return "minecraft:mangrove_pressure_plate"
            case .cherryPressurePlate:                      return "minecraft:cherry_pressure_plate"
            case .bambooPressurePlate:                      return "minecraft:bamboo_pressure_plate"
            case .crimsonPressurePlate:                     return "minecraft:crimson_pressure_plate"
            case .warpedPressurePlate:                      return "minecraft:warped_pressure_plate"
            case .stonePressurePlate:                       return "minecraft:stone_pressure_plate"
            case .lightWeightedPressurePlate:               return "minecraft:light_weighted_pressure_plate"
            case .heavyWeightedPressurePlate:               return "minecraft:heavy_weighted_pressure_plate"
            case .polishedBlackstonePressurePlate:          return "minecraft:polished_blackstone_pressure_plate"

            case .redstoneWire:                             return "minecraft:redstone_wire"
            case .redstoneTorch:                            return "minecraft:redstone_torch"
            case .unlitRedstoneTorch:                       return "minecraft:unlit_redstone_torch"
            case .lever:                                    return "minecraft:lever"
            case .tripwireHook:                             return "minecraft:tripwire_hook"
            case .tripWire:                                 return "minecraft:trip_wire"
            case .redstoneLamp:                             return "minecraft:redstone_lamp"
            case .litRedstoneLamp:                          return "minecraft:lit_redstone_lamp"
            case .observer:                                 return "minecraft:observer"
            case .daylightDetector:                         return "minecraft:daylight_detector"
            case .daylightDetectorInverted:                 return "minecraft:daylight_detector_inverted"
            case .poweredRepeater:                          return "minecraft:powered_repeater"
            case .unpoweredRepeater:                        return "minecraft:unpowered_repeater"
            case .poweredComparator:                        return "minecraft:powered_comparator"
            case .unpoweredComparator:                      return "minecraft:unpowered_comparator"
            case .hopper:                                   return "minecraft:hopper"
            case .dropper:                                  return "minecraft:dropper"
            case .dispenser:                                return "minecraft:dispenser"
            case .piston:                                   return "minecraft:piston"
            case .pistonArmCollision:                       return "minecraft:piston_arm_collision"
            case .stickyPiston:                             return "minecraft:sticky_piston"
            case .stickyPistonArmCollision:                 return "minecraft:sticky_piston_arm_collision"
            case .tnt:                                      return "minecraft:tnt"
            case .target:                                   return "minecraft:target"
            case .slime:                                    return "minecraft:slime"
            case .honeyBlock:                               return "minecraft:honey_block"

            /* ---------- ---------- ---------- Colored Blocks ---------- ---------- ---------- */
            case .bed:                                      return "minecraft:bed"
            case .standingBanner:                           return "minecraft:standing_banner"
            case .wallBanner:                               return "minecraft:wall_banner"

            case .tintedGlass:                              return "minecraft:tinted_glass"
            case .glass:                                    return "minecraft:glass"
            case .glassPane:                                return "minecraft:glass_pane"
            case .whiteStainedGlass:                        return "minecraft:stained_glass"
            case .lightGrayStainedGlass:                    return "minecraft:stained_glass"
            case .grayStainedGlass:                         return "minecraft:stained_glass"
            case .blackStainedGlass:                        return "minecraft:stained_glass"
            case .brownStainedGlass:                        return "minecraft:stained_glass"
            case .redStainedGlass:                          return "minecraft:stained_glass"
            case .orangeStainedGlass:                       return "minecraft:stained_glass"
            case .yellowStainedGlass:                       return "minecraft:stained_glass"
            case .limeStainedGlass:                         return "minecraft:stained_glass"
            case .greenStainedGlass:                        return "minecraft:stained_glass"
            case .cyanStainedGlass:                         return "minecraft:stained_glass"
            case .lightBlueStainedGlass:                    return "minecraft:stained_glass"
            case .blueStainedGlass:                         return "minecraft:stained_glass"
            case .purpleStainedGlass:                       return "minecraft:stained_glass"
            case .magentaStainedGlass:                      return "minecraft:stained_glass"
            case .pinkStainedGlass:                         return "minecraft:stained_glass"
            case .whiteStainedGlassPane:                    return "minecraft:stained_glass_pane"
            case .lightGrayStainedGlassPane:                return "minecraft:stained_glass_pane"
            case .grayStainedGlassPane:                     return "minecraft:stained_glass_pane"
            case .blackStainedGlassPane:                    return "minecraft:stained_glass_pane"
            case .brownStainedGlassPane:                    return "minecraft:stained_glass_pane"
            case .redStainedGlassPane:                      return "minecraft:stained_glass_pane"
            case .orangeStainedGlassPane:                   return "minecraft:stained_glass_pane"
            case .yellowStainedGlassPane:                   return "minecraft:stained_glass_pane"
            case .limeStainedGlassPane:                     return "minecraft:stained_glass_pane"
            case .greenStainedGlassPane:                    return "minecraft:stained_glass_pane"
            case .cyanStainedGlassPane:                     return "minecraft:stained_glass_pane"
            case .lightBlueStainedGlassPane:                return "minecraft:stained_glass_pane"
            case .blueStainedGlassPane:                     return "minecraft:stained_glass_pane"
            case .purpleStainedGlassPane:                   return "minecraft:stained_glass_pane"
            case .magentaStainedGlassPane:                  return "minecraft:stained_glass_pane"
            case .pinkStainedGlassPane:                     return "minecraft:stained_glass_pane"

            case .undyedShulkerBox:                         return "minecraft:undyed_shulker_box"
            case .whiteShulkerBox:                          return "minecraft:white_shulker_box"
            case .lightGrayShulkerBox:                      return "minecraft:light_gray_shulker_box"
            case .grayShulkerBox:                           return "minecraft:gray_shulker_box"
            case .blackShulkerBox:                          return "minecraft:black_shulker_box"
            case .brownShulkerBox:                          return "minecraft:brown_shulker_box"
            case .redShulkerBox:                            return "minecraft:red_shulker_box"
            case .orangeShulkerBox:                         return "minecraft:orange_shulker_box"
            case .yellowShulkerBox:                         return "minecraft:yellow_shulker_box"
            case .limeShulkerBox:                           return "minecraft:lime_shulker_box"
            case .greenShulkerBox:                          return "minecraft:green_shulker_box"
            case .cyanShulkerBox:                           return "minecraft:cyan_shulker_box"
            case .lightBlueShulkerBox:                      return "minecraft:light_blue_shulker_box"
            case .blueShulkerBox:                           return "minecraft:blue_shulker_box"
            case .purpleShulkerBox:                         return "minecraft:purple_shulker_box"
            case .magentaShulkerBox:                        return "minecraft:magenta_shulker_box"
            case .pinkShulkerBox:                           return "minecraft:pink_shulker_box"

            // case .wool:                                  return "minecraft:wool"
            case .whiteWool:                                return "minecraft:white_wool"
            case .lightGrayWool:                            return "minecraft:light_gray_wool"
            case .grayWool:                                 return "minecraft:gray_wool"
            case .blackWool:                                return "minecraft:black_wool"
            case .brownWool:                                return "minecraft:brown_wool"
            case .redWool:                                  return "minecraft:red_wool"
            case .orangeWool:                               return "minecraft:orange_wool"
            case .yellowWool:                               return "minecraft:yellow_wool"
            case .limeWool:                                 return "minecraft:lime_wool"
            case .greenWool:                                return "minecraft:green_wool"
            case .cyanWool:                                 return "minecraft:cyan_wool"
            case .lightBlueWool:                            return "minecraft:light_blue_wool"
            case .blueWool:                                 return "minecraft:blue_wool"
            case .purpleWool:                               return "minecraft:purple_wool"
            case .magentaWool:                              return "minecraft:magenta_wool"
            case .pinkWool:                                 return "minecraft:pink_wool"

            // case .carpet:                                return "minecraft:carpet"
            case .whiteCarpet:                              return "minecraft:white_carpet"
            case .lightGrayCarpet:                          return "minecraft:light_gray_carpet"
            case .grayCarpet:                               return "minecraft:gray_carpet"
            case .blackCarpet:                              return "minecraft:black_carpet"
            case .brownCarpet:                              return "minecraft:brown_carpet"
            case .redCarpet:                                return "minecraft:red_carpet"
            case .orangeCarpet:                             return "minecraft:orange_carpet"
            case .yellowCarpet:                             return "minecraft:yellow_carpet"
            case .limeCarpet:                               return "minecraft:lime_carpet"
            case .greenCarpet:                              return "minecraft:green_carpet"
            case .cyanCarpet:                               return "minecraft:cyan_carpet"
            case .lightBlueCarpet:                          return "minecraft:light_blue_carpet"
            case .blueCarpet:                               return "minecraft:blue_carpet"
            case .purpleCarpet:                             return "minecraft:purple_carpet"
            case .magentaCarpet:                            return "minecraft:magenta_carpet"
            case .pinkCarpet:                               return "minecraft:pink_carpet"

            case .candle:                                   return "minecraft:candle"
            case .whiteCandle:                              return "minecraft:white_candle"
            case .lightGrayCandle:                          return "minecraft:light_gray_candle"
            case .grayCandle:                               return "minecraft:gray_candle"
            case .blackCandle:                              return "minecraft:black_candle"
            case .brownCandle:                              return "minecraft:brown_candle"
            case .redCandle:                                return "minecraft:red_candle"
            case .orangeCandle:                             return "minecraft:orange_candle"
            case .yellowCandle:                             return "minecraft:yellow_candle"
            case .limeCandle:                               return "minecraft:lime_candle"
            case .greenCandle:                              return "minecraft:green_candle"
            case .cyanCandle:                               return "minecraft:cyan_candle"
            case .lightBlueCandle:                          return "minecraft:light_blue_candle"
            case .blueCandle:                               return "minecraft:blue_candle"
            case .purpleCandle:                             return "minecraft:purple_candle"
            case .magentaCandle:                            return "minecraft:magenta_candle"
            case .pinkCandle:                               return "minecraft:pink_candle"

            case .cake:                                     return "minecraft:cake"
            case .candleCake:                               return "minecraft:candle_cake"
            case .whiteCandleCake:                          return "minecraft:white_candle_cake"
            case .lightGrayCandleCake:                      return "minecraft:light_gray_candle_cake"
            case .grayCandleCake:                           return "minecraft:gray_candle_cake"
            case .blackCandleCake:                          return "minecraft:black_candle_cake"
            case .brownCandleCake:                          return "minecraft:brown_candle_cake"
            case .redCandleCake:                            return "minecraft:red_candle_cake"
            case .orangeCandleCake:                         return "minecraft:orange_candle_cake"
            case .yellowCandleCake:                         return "minecraft:yellow_candle_cake"
            case .limeCandleCake:                           return "minecraft:lime_candle_cake"
            case .greenCandleCake:                          return "minecraft:green_candle_cake"
            case .cyanCandleCake:                           return "minecraft:cyan_candle_cake"
            case .lightBlueCandleCake:                      return "minecraft:light_blue_candle_cake"
            case .blueCandleCake:                           return "minecraft:blue_candle_cake"
            case .purpleCandleCake:                         return "minecraft:purple_candle_cake"
            case .magentaCandleCake:                        return "minecraft:magenta_candle_cake"
            case .pinkCandleCake:                           return "minecraft:pink_candle_cake"

            case .whiteConcretePowder:                      return "minecraft:concrete_powder"
            case .lightGrayConcretePowder:                  return "minecraft:concrete_powder"
            case .grayConcretePowder:                       return "minecraft:concrete_powder"
            case .blackConcretePowder:                      return "minecraft:concrete_powder"
            case .brownConcretePowder:                      return "minecraft:concrete_powder"
            case .redConcretePowder:                        return "minecraft:concrete_powder"
            case .orangeConcretePowder:                     return "minecraft:concrete_powder"
            case .yellowConcretePowder:                     return "minecraft:concrete_powder"
            case .limeConcretePowder:                       return "minecraft:concrete_powder"
            case .greenConcretePowder:                      return "minecraft:concrete_powder"
            case .cyanConcretePowder:                       return "minecraft:concrete_powder"
            case .lightBlueConcretePowder:                  return "minecraft:concrete_powder"
            case .blueConcretePowder:                       return "minecraft:concrete_powder"
            case .purpleConcretePowder:                     return "minecraft:concrete_powder"
            case .magentaConcretePowder:                    return "minecraft:concrete_powder"
            case .pinkConcretePowder:                       return "minecraft:concrete_powder"

            case .concrete:                                 return "minecraft:concrete"
            case .whiteConcrete:                            return "minecraft:white_concrete"
            case .lightGrayConcrete:                        return "minecraft:light_gray_concrete"
            case .grayConcrete:                             return "minecraft:gray_concrete"
            case .blackConcrete:                            return "minecraft:black_concrete"
            case .brownConcrete:                            return "minecraft:brown_concrete"
            case .redConcrete:                              return "minecraft:red_concrete"
            case .orangeConcrete:                           return "minecraft:orange_concrete"
            case .yellowConcrete:                           return "minecraft:yellow_concrete"
            case .limeConcrete:                             return "minecraft:lime_concrete"
            case .greenConcrete:                            return "minecraft:green_concrete"
            case .cyanConcrete:                             return "minecraft:cyan_concrete"
            case .lightBlueConcrete:                        return "minecraft:light_blue_concrete"
            case .blueConcrete:                             return "minecraft:blue_concrete"
            case .purpleConcrete:                           return "minecraft:purple_concrete"
            case .magentaConcrete:                          return "minecraft:magenta_concrete"
            case .pinkConcrete:                             return "minecraft:pink_concrete"

            case .clay:                                     return "minecraft:clay"
            case .hardenedClay:                             return "minecraft:hardened_clay"
            case .whiteStainedHardenedClay:                 return "minecraft:stained_hardened_clay"
            case .lightGrayStainedHardenedClay:             return "minecraft:stained_hardened_clay"
            case .grayStainedHardenedClay:                  return "minecraft:stained_hardened_clay"
            case .blackStainedHardenedClay:                 return "minecraft:stained_hardened_clay"
            case .brownStainedHardenedClay:                 return "minecraft:stained_hardened_clay"
            case .redStainedHardenedClay:                   return "minecraft:stained_hardened_clay"
            case .orangeStainedHardenedClay:                return "minecraft:stained_hardened_clay"
            case .yellowStainedHardenedClay:                return "minecraft:stained_hardened_clay"
            case .limeStainedHardenedClay:                  return "minecraft:stained_hardened_clay"
            case .greenStainedHardenedClay:                 return "minecraft:stained_hardened_clay"
            case .cyanStainedHardenedClay:                  return "minecraft:stained_hardened_clay"
            case .lightBlueStainedHardenedClay:             return "minecraft:stained_hardened_clay"
            case .blueStainedHardenedClay:                  return "minecraft:stained_hardened_clay"
            case .purpleStainedHardenedClay:                return "minecraft:stained_hardened_clay"
            case .magentaStainedHardenedClay:               return "minecraft:stained_hardened_clay"
            case .pinkStainedHardenedClay:                  return "minecraft:stained_hardened_clay"

            case .whiteGlazedTerracotta:                    return "minecraft:white_glazed_terracotta"
            case .silverGlazedTerracotta:                   return "minecraft:silver_glazed_terracotta"
            case .grayGlazedTerracotta:                     return "minecraft:gray_glazed_terracotta"
            case .blackGlazedTerracotta:                    return "minecraft:black_glazed_terracotta"
            case .brownGlazedTerracotta:                    return "minecraft:brown_glazed_terracotta"
            case .redGlazedTerracotta:                      return "minecraft:red_glazed_terracotta"
            case .orangeGlazedTerracotta:                   return "minecraft:orange_glazed_terracotta"
            case .yellowGlazedTerracotta:                   return "minecraft:yellow_glazed_terracotta"
            case .limeGlazedTerracotta:                     return "minecraft:lime_glazed_terracotta"
            case .greenGlazedTerracotta:                    return "minecraft:green_glazed_terracotta"
            case .cyanGlazedTerracotta:                     return "minecraft:cyan_glazed_terracotta"
            case .lightBlueGlazedTerracotta:                return "minecraft:light_blue_glazed_terracotta"
            case .blueGlazedTerracotta:                     return "minecraft:blue_glazed_terracotta"
            case .purpleGlazedTerracotta:                   return "minecraft:purple_glazed_terracotta"
            case .magentaGlazedTerracotta:                  return "minecraft:magenta_glazed_terracotta"
            case .pinkGlazedTerracotta:                     return "minecraft:pink_glazed_terracotta"

            case .tubeCoralBlock:                           return "minecraft:coral_block"
            case .brainCoralBlock:                          return "minecraft:coral_block"
            case .bubbleCoralBlock:                         return "minecraft:coral_block"
            case .fireCoralBlock:                           return "minecraft:coral_block"
            case .hornCoralBlock:                           return "minecraft:coral_block"
            case .deadTubeCoralBlock:                       return "minecraft:coral_block"
            case .deadBrainCoralBlock:                      return "minecraft:coral_block"
            case .deadBubbleCoralBlock:                     return "minecraft:coral_block"
            case .deadFireCoralBlock:                       return "minecraft:coral_block"
            case .deadHornCoralBlock:                       return "minecraft:coral_block"

            case .fireCoral:                                return "minecraft:fire_coral"
            case .brainCoral:                               return "minecraft:brain_coral"
            case .bubbleCoral:                              return "minecraft:bubble_coral"
            case .tubeCoral:                                return "minecraft:tube_coral"
            case .hornCoral:                                return "minecraft:horn_coral"
            case .deadFireCoral:                            return "minecraft:dead_fire_coral"
            case .deadBrainCoral:                           return "minecraft:dead_brain_coral"
            case .deadBubbleCoral:                          return "minecraft:dead_bubble_coral"
            case .deadTubeCoral:                            return "minecraft:dead_tube_coral"
            case .deadHornCoral:                            return "minecraft:dead_horn_coral"

            case .tubeCoralFan:                             return "minecraft:coral_fan"
            case .brainCoralFan:                            return "minecraft:coral_fan"
            case .bubbleCoralFan:                           return "minecraft:coral_fan"
            case .fireCoralFan:                             return "minecraft:coral_fan"
            case .hornCoralFan:                             return "minecraft:coral_fan"

            case .deadTubeCoralFan:                         return "minecraft:coral_fan_dead"
            case .deadBrainCoralFan:                        return "minecraft:coral_fan_dead"
            case .deadBubbleCoralFan:                       return "minecraft:coral_fan_dead"
            case .deadFireCoralFan:                         return "minecraft:coral_fan_dead"
            case .deadHornCoralFan:                         return "minecraft:coral_fan_dead"

            case .tubeCoralHang:                            return "minecraft:coral_fan_hang"
            case .brainCoralHang:                           return "minecraft:coral_fan_hang"
            case .deadTubeCoralHang:                        return "minecraft:coral_fan_hang"
            case .deadBrainCoralHang:                       return "minecraft:coral_fan_hang"
            case .bubbleCoralHang:                          return "minecraft:coral_fan_hang2"
            case .fireCoralHang:                            return "minecraft:coral_fan_hang2"
            case .deadBubbleCoralHang:                      return "minecraft:coral_fan_hang2"
            case .deadFireCoralHang:                        return "minecraft:coral_fan_hang2"
            case .hornCoralHang:                            return "minecraft:coral_fan_hang3"
            case .deadHornCoralHang:                        return "minecraft:coral_fan_hang3"

            /* ---------- ---------- ---------- Other ---------- ---------- ---------- */
            case .clientRequestPlaceholderBlock:            return "minecraft:client_request_placeholder_block"
            case .invisibleBedrock:                         return "minecraft:invisible_bedrock"
            case .reserved6:                                return "minecraft:reserved6"
            case .netherreactor:                            return "minecraft:netherreactor"
            case .glowingobsidian:                          return "minecraft:glowingobsidian"
            case .stonecutter:                              return "minecraft:stonecutter"
            case .infoUpdate:                               return "minecraft:info_update"
            case .infoUpdate2:                              return "minecraft:info_update2"
        }
    }
}
